/**
 * Modern layout class names — styles live in design/tokens/modern.css.
 * (Tailwind utilities in string constants are not reliably emitted in this project's CSS build.)
 */
export const modernLayout = {
  sectionX: "modern-section-x",
  container: "modern-container",
  heroPt: "modern-hero-pt",
  heroPb: "modern-hero-pb",
  sectionPy: "modern-section-py",
  sectionPyLarge: "modern-section-py-lg",
  statsSection: "modern-stats-section",
  statsSectionAfterLogos: "modern-stats-section--after-logos",
  sectionDivider: "modern-section-divider",
  dividerBand: "modern-divider-band",
  belowDividerPt: "modern-below-divider",
  sectionHeaderMb: "modern-section-header-mb",
  cardPad: "modern-card-pad",
  cardGrid: "modern-card-grid",
  statsGrid: "modern-stats-grid",
  hr: "modern-hr",
  contactInfoGrid: "modern-contact-info-grid",
  contactCard: "modern-contact-card",
  contactHero: "modern-contact-hero",
  contactSubtitle: "modern-contact-subtitle",
  contactBlocks: "modern-contact-blocks",
  aboutHero: "modern-about-hero",
  aboutHeadline: "modern-about-headline",
  aboutLead: "modern-about-lead",
  aboutActions: "modern-about-actions",
  aboutBioSection: "modern-about-bio-section",
  aboutBioCard: "modern-about-bio-card",
  aboutBioGrid: "modern-about-bio-grid",
  aboutBioMain: "modern-about-bio-main",
  aboutBioSkeleton: "modern-about-bio-skeleton",
  aboutInfoStack: "modern-about-info-stack",
  aboutInfoItem: "modern-about-info-item",
  aboutInfoValue: "modern-about-info-value",
  aboutSection: "modern-about-section",
  aboutCardGrid3: "modern-about-card-grid-3",
  aboutCardGrid2: "modern-about-card-grid-2",
  aboutInlineCard: "modern-about-inline-card",
  aboutListItem: "modern-about-list-item",
  navDesktop: "modern-nav-desktop",
  navInner: "modern-nav-inner",
  navMobileLeading: "modern-nav-mobile-leading",
  navMobileTrailing: "modern-nav-mobile-trailing",
  navMenuToggle: "modern-nav-menu-toggle",
  navMobileDrawerRoot: "modern-nav-drawer-root",
  navMobileDrawerBackdrop: "modern-nav-drawer-backdrop",
  navMobileDrawer: "modern-nav-drawer",
  navMobileDrawerInner: "modern-nav-drawer-inner",
  navMobileDrawerLink: "modern-nav-drawer-link",
  navMobileMenu: "modern-nav-mobile-menu",
  footerPy: "modern-footer-py",
  projectDetailShell: "modern-project-detail-shell",
} as const;
